#!/bin/bash

host=$1

mv results results.bak

for p in 90 270 512 4K 16K
do
  for i in 1 2 3
  do
    ./bin/netperf  -t TCP_RR -p 20000  -H $host -I 99,5 -- -O MIN_LATENCY,MAX_LATENCY,P50_LATENCY,P90_LATENCY,P99_LATENCY,MEAN_LATENCY,STDDEV_LATENCY,RT_LATENCY,THROUGHPUT,THROUGHPUT_UNITS,REQUEST_SIZE,RESPONSE_SIZE,CONFIDENCE_LEVEL,CONFIDENCE_INTERVAL,CONFIDENCE_ITERATION -P 20001 -r $p,$p  >> results
  done
done
